### ISSUE TITLE
Cannot find theme in VSC

### ISSUE THREAD

**Issue by SomeKittens** [Tyriar/vscode-theme-generator#33]
From the docs: 

> Make your changes to the colors in index.ts and hit F5 to build the theme and launch the a new VS Code window with your theme available in the command palette (ctrl/cmd+shift+p > "Color Theme").

Made my changes, hit f5.  Nothing happened.  Ran the build task via the tasks panel.  Theme was built, but a new VSC window was never opened.

OSX, VSC v1.12.0

**Comment by SomeKittens** [comment]
Apologies, specifically I'm using the quickstart here: https://github.com/Tyriar/vscode-theme-generator-quick-start

**Comment by SomeKittens** [comment]
Managed to get it working manually via debug.  Not sure why f5 doesn't work here.

**Comment by Tyriar** [comment]
@SomeKittens hmm, do you have a keybinding that overrides debug maybe? I think it should be F5 by default on all platforms.
