### ISSUE TITLE
Web based interface

### ISSUE THREAD

**Issue by simonvizzini** [Tyriar/vscode-theme-generator#37]
A theme generator is a great idea! I'd like to take it further and offer a web interface for the theme generator. But a 100% accurate preview would be essential to make such a web interface really useful. My first thought was to simply use the standalone Monaco editor for the previews, but unfortunately I found out that Monaco doesn't support TextMate grammars (as described in the [Monaco FAQ](https://github.com/Microsoft/monaco-editor#faq)) Only hope seems to be WebAssembly, but I don't think it will gain that much traction anytime soon.

So my conclusion is it won't be possible to do at the moment. But maybe you have an idea how a proper preview could be implemented, outside the context of VS Code?

**Comment by Tyriar** [comment]
Interesting idea!

Yeah as far as I know you can't do this as the textmate engine relies on the native oniguruma regex library. You could do it if you had a server that could run the native lib of course but that's a little more tricky.

Another issue with a web-based interface is you need more files than just the json to actually publish the extension. So you'd want to define exactly what your web interface is trying to accomplish before you get started, that would determine how hard it is going to be to implement :smile:

**Comment by simonvizzini** [comment]
Thanks, that's what I thought.

The first iteration of course wouldn't support direct publishing of theme extensions to the market place. What I had in mind was simply a theme.json as output, which then could be published manually.

First iteration would be really simple, just a bunch of color pickers to pick the basic colors, plus the option to fine tune the other rules, just like you do it in the demo folder with the sapphire theme. Would've been easy enough to implement, except for the preview part... also I'm not exactly sure how running oniguruma on a server would help here. In the end the preview would be just a bunch of HTML and CSS.

Anyway, implementing something server side would go beyond the scope of my available time. But I'll keep an eye on Monaco, maybe it will support TM grammars in a couple of years :smile:
