### ISSUE TITLE
Suggestion: Terminal Panel Background

### ISSUE THREAD

**Issue by sgtoj** [Tyriar/vscode-theme-generator#39]
### Suggestion

Change the terminal panel background to be slightly different than the `sideBar`. I changed the color to match the background as the the `activityBar`.

```js
// theme-extend: sapphire (dim)
"workbench.colorCustomizations": {
  "panel.background": "#0b121c"
}
```

###  Preview

![Example](http://i.imgur.com/ac9I5K3.png)

Thought I would throw this suggestion out there before I made my own theme extension.

**Comment by Tyriar** [comment]
This was an intentional decision to make the "main workbench parts" (panel+side bar) the same color. There are options I have in mind for the future, see https://github.com/Tyriar/vscode-theme-generator/issues/29#issuecomment-300894336 and https://github.com/Tyriar/vscode-theme-generator/issues/40
