### ISSUE TITLE
very unusual request

### ISSUE THREAD

**Issue by corem96** [Tyriar/vscode-theme-generator#44]
I tried not to open an issue for this particular request, but I can't contact @Tyriar directly through github or via email address or any other private comunication channel... **so only for this time I wil do this**.
you have posted an image of the vscode window and I was wonder if you could tell me **what is the font** you where using in the code editor. I have tried to get it in most common font websites but i can't find it. This is the image you have posted:

![example](https://user-images.githubusercontent.com/18492412/34219060-3a9fad46-e56d-11e7-9845-4747c427c066.png)

sorry for the inconvenient I may caused.

**Comment by Tyriar** [comment]
It's Hack http://sourcefoundry.org/hack/, hope you enjoy it :smiley:

I'm pretty responsive on Twitter if you need to chat in the future/if you have one https://twitter.com/Tyriar
