### ISSUE TITLE
Is it intentionally that functions and methods have different colors?

### ISSUE THREAD

**Issue by usernamehw** [Tyriar/vscode-theme-generator#45]
```javascript
function fun(){}
let fun = () => 0;

class Cla {
    meth() {}
    meth = () => 0;
    meth = function() {}
}
```
Generated result:
![screenshot 10](https://user-images.githubusercontent.com/9638156/40575564-dde62824-60ef-11e8-8c4d-c9fe28870e59.png)

All of my installed themes use them consistently:
![screenshot 11](https://user-images.githubusercontent.com/9638156/40575586-2354a98a-60f0-11e8-8b4f-dca3e27b5bce.png)

**Comment by Tyriar** [comment]
Line 1: Yes, this is covered by the `function` color:

https://github.com/Tyriar/vscode-theme-generator/blob/0901714136fa70a92e5533055943759e5a163b0c/src/rules.ts#L94

Line 2: Yes, this is the variable/identifier color:

https://github.com/Tyriar/vscode-theme-generator/blob/0901714136fa70a92e5533055943759e5a163b0c/src/rules.ts#L76

Line 5: No, this should use the `classMember` color, currently:

https://github.com/Tyriar/vscode-theme-generator/blob/0901714136fa70a92e5533055943759e5a163b0c/src/rules.ts#L80

Line 6: Yes, this is the `classMember` color. I didn't want to differentiate functions and non-function members:

https://github.com/Tyriar/vscode-theme-generator/blob/0901714136fa70a92e5533055943759e5a163b0c/src/rules.ts#L93
