### ISSUE TITLE
Interpolated characters not highlighted

### ISSUE THREAD

**Issue by usernamehw** [Tyriar/vscode-theme-generator#47]
In JS/TS represented by `${}`:
```javascript 
let str = `text${text}text` 
```

**Comment by Tyriar** [comment]
I think the grammar must have changed in VS Code:

https://github.com/Tyriar/vscode-theme-generator/blob/0901714136fa70a92e5533055943759e5a163b0c/src/rules.ts#L95

Or this never worked.
