### ISSUE TITLE
When running "npm install" in vscode to set this up, it returns the error "node_modules/@types/node/index.d.ts:20:1 - error TS1084: Invalid 'reference' directive syntax."

### ISSUE THREAD

**Issue by IntangibleMatter** [Tyriar/vscode-theme-generator#59]
Basically the title. I don't really know anything about TypeScript, so I can't resolve this issue myself.

The line it seems to be taking issue with is:
`/// <reference lib="es2015" />`

So I can't run it.

**Comment by Tyriar** [comment]
I can repro, the fix is probably updating `typescript` or `@types/node` (v10 seems safe)

**Comment by Lvthr** [comment]
Got it working by removing '^' from the version numbers for both the "@types/node" and "typescript" entries in the devDependencies section of the package.json, deleting node_modules directory and running npm install again. 
New devDependencies entry in package.json:
```js
"devDependencies": {
    "@types/node": "7.0.10",
    "typescript": "2.2.1",
    "vscode-theme-generator": "*"
}
```
Removing node_modules, reinstalling modules and running. 
```bash
rm -rf ./node_modules/ && npm install
npm start
```
Doesn't seem like a long-term solution, given the old versions used for both these dependencies, but might help anyone in the same situation.

**Comment by seadb** [comment]
Thank you so much @Lvthr, I was able to use this!

**Comment by ayush-lal** [comment]
Thanks so much @Lvthr, that solved my issue as well :)

**Comment by Tyriar** [comment]
Thanks for helping people with the workaround, I'd accept a PR to update the deps if everything builds fine.

**Comment by Tyriar** [comment]
Fixed by https://github.com/Tyriar/vscode-theme-generator/pull/60
